// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: proto/miners.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCoinIDByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coin string `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
}

func (x *GetCoinIDByNameRequest) Reset() {
	*x = GetCoinIDByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinIDByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinIDByNameRequest) ProtoMessage() {}

func (x *GetCoinIDByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinIDByNameRequest.ProtoReflect.Descriptor instead.
func (*GetCoinIDByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{0}
}

func (x *GetCoinIDByNameRequest) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

type GetCoinIDByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetCoinIDByNameResponse) Reset() {
	*x = GetCoinIDByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCoinIDByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCoinIDByNameResponse) ProtoMessage() {}

func (x *GetCoinIDByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCoinIDByNameResponse.ProtoReflect.Descriptor instead.
func (*GetCoinIDByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{1}
}

func (x *GetCoinIDByNameResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateWalletRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CoinId       int64  `protobuf:"varint,2,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	Name         string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IsSolo       bool   `protobuf:"varint,4,opt,name=is_solo,json=isSolo,proto3" json:"is_solo,omitempty"`
	RewardMethod string `protobuf:"bytes,5,opt,name=reward_method,json=rewardMethod,proto3" json:"reward_method,omitempty"`
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWalletRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateWalletRequest) GetCoinId() int64 {
	if x != nil {
		return x.CoinId
	}
	return 0
}

func (x *CreateWalletRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateWalletRequest) GetIsSolo() bool {
	if x != nil {
		return x.IsSolo
	}
	return false
}

func (x *CreateWalletRequest) GetRewardMethod() string {
	if x != nil {
		return x.RewardMethod
	}
	return ""
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWalletResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type CreateWorkerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CoinId       int64  `protobuf:"varint,2,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	Workerfull   string `protobuf:"bytes,3,opt,name=workerfull,proto3" json:"workerfull,omitempty"`
	Wallet       string `protobuf:"bytes,4,opt,name=wallet,proto3" json:"wallet,omitempty"`
	Worker       string `protobuf:"bytes,5,opt,name=worker,proto3" json:"worker,omitempty"`
	ServerId     string `protobuf:"bytes,6,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	Ip           string `protobuf:"bytes,7,opt,name=ip,proto3" json:"ip,omitempty"`
	IsSolo       bool   `protobuf:"varint,8,opt,name=is_solo,json=isSolo,proto3" json:"is_solo,omitempty"`
	RewardMethod string `protobuf:"bytes,9,opt,name=reward_method,json=rewardMethod,proto3" json:"reward_method,omitempty"`
}

func (x *CreateWorkerRequest) Reset() {
	*x = CreateWorkerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerRequest) ProtoMessage() {}

func (x *CreateWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerRequest.ProtoReflect.Descriptor instead.
func (*CreateWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{4}
}

func (x *CreateWorkerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateWorkerRequest) GetCoinId() int64 {
	if x != nil {
		return x.CoinId
	}
	return 0
}

func (x *CreateWorkerRequest) GetWorkerfull() string {
	if x != nil {
		return x.Workerfull
	}
	return ""
}

func (x *CreateWorkerRequest) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *CreateWorkerRequest) GetWorker() string {
	if x != nil {
		return x.Worker
	}
	return ""
}

func (x *CreateWorkerRequest) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *CreateWorkerRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *CreateWorkerRequest) GetIsSolo() bool {
	if x != nil {
		return x.IsSolo
	}
	return false
}

func (x *CreateWorkerRequest) GetRewardMethod() string {
	if x != nil {
		return x.RewardMethod
	}
	return ""
}

type CreateWorkerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateWorkerResponse) Reset() {
	*x = CreateWorkerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWorkerResponse) ProtoMessage() {}

func (x *CreateWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWorkerResponse.ProtoReflect.Descriptor instead.
func (*CreateWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{5}
}

func (x *CreateWorkerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWalletIDByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Wallet       string `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	CoinId       int64  `protobuf:"varint,2,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	RewardMethod string `protobuf:"bytes,3,opt,name=reward_method,json=rewardMethod,proto3" json:"reward_method,omitempty"`
}

func (x *GetWalletIDByNameRequest) Reset() {
	*x = GetWalletIDByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletIDByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletIDByNameRequest) ProtoMessage() {}

func (x *GetWalletIDByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletIDByNameRequest.ProtoReflect.Descriptor instead.
func (*GetWalletIDByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{6}
}

func (x *GetWalletIDByNameRequest) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *GetWalletIDByNameRequest) GetCoinId() int64 {
	if x != nil {
		return x.CoinId
	}
	return 0
}

func (x *GetWalletIDByNameRequest) GetRewardMethod() string {
	if x != nil {
		return x.RewardMethod
	}
	return ""
}

type GetWalletIDByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWalletIDByNameResponse) Reset() {
	*x = GetWalletIDByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWalletIDByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletIDByNameResponse) ProtoMessage() {}

func (x *GetWalletIDByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletIDByNameResponse.ProtoReflect.Descriptor instead.
func (*GetWalletIDByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{7}
}

func (x *GetWalletIDByNameResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWorkerIDByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Workerfull   string `protobuf:"bytes,1,opt,name=workerfull,proto3" json:"workerfull,omitempty"`
	CoinId       int64  `protobuf:"varint,2,opt,name=coin_id,json=coinId,proto3" json:"coin_id,omitempty"`
	RewardMethod string `protobuf:"bytes,3,opt,name=reward_method,json=rewardMethod,proto3" json:"reward_method,omitempty"`
}

func (x *GetWorkerIDByNameRequest) Reset() {
	*x = GetWorkerIDByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkerIDByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerIDByNameRequest) ProtoMessage() {}

func (x *GetWorkerIDByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerIDByNameRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerIDByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{8}
}

func (x *GetWorkerIDByNameRequest) GetWorkerfull() string {
	if x != nil {
		return x.Workerfull
	}
	return ""
}

func (x *GetWorkerIDByNameRequest) GetCoinId() int64 {
	if x != nil {
		return x.CoinId
	}
	return 0
}

func (x *GetWorkerIDByNameRequest) GetRewardMethod() string {
	if x != nil {
		return x.RewardMethod
	}
	return ""
}

type GetWorkerIDByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetWorkerIDByNameResponse) Reset() {
	*x = GetWorkerIDByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWorkerIDByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerIDByNameResponse) ProtoMessage() {}

func (x *GetWorkerIDByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerIDByNameResponse.ProtoReflect.Descriptor instead.
func (*GetWorkerIDByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{9}
}

func (x *GetWorkerIDByNameResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Сообщение для деталей ошибки
type MPError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Method      string `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`           // метод, где возникла ошибка
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // описание
}

func (x *MPError) Reset() {
	*x = MPError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_miners_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MPError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPError) ProtoMessage() {}

func (x *MPError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_miners_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPError.ProtoReflect.Descriptor instead.
func (*MPError) Descriptor() ([]byte, []int) {
	return file_proto_miners_proto_rawDescGZIP(), []int{10}
}

func (x *MPError) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *MPError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_proto_miners_proto protoreflect.FileDescriptor

var file_proto_miners_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x2c, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x69, 0x6e, 0x22, 0x29, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x69, 0x6e, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61,
	0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63,
	0x6f, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x73,
	0x6f, 0x6c, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x53, 0x6f, 0x6c,
	0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xf9,
	0x01, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x66, 0x75, 0x6c, 0x6c, 0x12,
	0x16, 0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x73, 0x5f, 0x73, 0x6f, 0x6c, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69,
	0x73, 0x53, 0x6f, 0x6c, 0x6f, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65,
	0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x26, 0x0a, 0x14, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x70, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49,
	0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63, 0x6f, 0x69, 0x6e, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x78, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44,
	0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a,
	0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x66, 0x75, 0x6c, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x66, 0x75, 0x6c, 0x6c, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x6f, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06,
	0x63, 0x6f, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x77, 0x61, 0x72, 0x64,
	0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72,
	0x65, 0x77, 0x61, 0x72, 0x64, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x22, 0x2b, 0x0a, 0x19, 0x47,
	0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x07, 0x4d, 0x50, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x32, 0x99, 0x03,
	0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x4e, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69,
	0x6e, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f, 0x69, 0x6e, 0x49,
	0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x45, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x12,
	0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70,
	0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x57, 0x61, 0x6c,
	0x6c, 0x65, 0x74, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x49, 0x44, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1d, 0x5a, 0x1b, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_miners_proto_rawDescOnce sync.Once
	file_proto_miners_proto_rawDescData = file_proto_miners_proto_rawDesc
)

func file_proto_miners_proto_rawDescGZIP() []byte {
	file_proto_miners_proto_rawDescOnce.Do(func() {
		file_proto_miners_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_miners_proto_rawDescData)
	})
	return file_proto_miners_proto_rawDescData
}

var file_proto_miners_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_miners_proto_goTypes = []interface{}{
	(*GetCoinIDByNameRequest)(nil),    // 0: grpc.GetCoinIDByNameRequest
	(*GetCoinIDByNameResponse)(nil),   // 1: grpc.GetCoinIDByNameResponse
	(*CreateWalletRequest)(nil),       // 2: grpc.CreateWalletRequest
	(*CreateWalletResponse)(nil),      // 3: grpc.CreateWalletResponse
	(*CreateWorkerRequest)(nil),       // 4: grpc.CreateWorkerRequest
	(*CreateWorkerResponse)(nil),      // 5: grpc.CreateWorkerResponse
	(*GetWalletIDByNameRequest)(nil),  // 6: grpc.GetWalletIDByNameRequest
	(*GetWalletIDByNameResponse)(nil), // 7: grpc.GetWalletIDByNameResponse
	(*GetWorkerIDByNameRequest)(nil),  // 8: grpc.GetWorkerIDByNameRequest
	(*GetWorkerIDByNameResponse)(nil), // 9: grpc.GetWorkerIDByNameResponse
	(*MPError)(nil),                   // 10: grpc.MPError
}
var file_proto_miners_proto_depIdxs = []int32{
	0, // 0: grpc.MinersService.GetCoinIDByName:input_type -> grpc.GetCoinIDByNameRequest
	2, // 1: grpc.MinersService.CreateWallet:input_type -> grpc.CreateWalletRequest
	4, // 2: grpc.MinersService.CreateWorker:input_type -> grpc.CreateWorkerRequest
	6, // 3: grpc.MinersService.GetWalletIDByName:input_type -> grpc.GetWalletIDByNameRequest
	8, // 4: grpc.MinersService.GetWorkerIDByName:input_type -> grpc.GetWorkerIDByNameRequest
	1, // 5: grpc.MinersService.GetCoinIDByName:output_type -> grpc.GetCoinIDByNameResponse
	3, // 6: grpc.MinersService.CreateWallet:output_type -> grpc.CreateWalletResponse
	5, // 7: grpc.MinersService.CreateWorker:output_type -> grpc.CreateWorkerResponse
	7, // 8: grpc.MinersService.GetWalletIDByName:output_type -> grpc.GetWalletIDByNameResponse
	9, // 9: grpc.MinersService.GetWorkerIDByName:output_type -> grpc.GetWorkerIDByNameResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_miners_proto_init() }
func file_proto_miners_proto_init() {
	if File_proto_miners_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_miners_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinIDByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCoinIDByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWalletRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWalletResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateWorkerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletIDByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWalletIDByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkerIDByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWorkerIDByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_miners_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MPError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_miners_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_miners_proto_goTypes,
		DependencyIndexes: file_proto_miners_proto_depIdxs,
		MessageInfos:      file_proto_miners_proto_msgTypes,
	}.Build()
	File_proto_miners_proto = out.File
	file_proto_miners_proto_rawDesc = nil
	file_proto_miners_proto_goTypes = nil
	file_proto_miners_proto_depIdxs = nil
}
